// Generated by cra-context-generator@1.2.0 on Sun, 26 Jun 2022 08:35:13 GMT.
// Do not edit this file manually unless you disabled its code generation.
import React from 'react';
import ReactDOM from 'react-dom';
import { History, Location } from 'history';
import { AppContextProvider, IAppState, AppState, DefaultAppState } from './appContext';
import { createChildren, getHistory, deserializePathname, serializePathname } from './contextBuilderUtils';

/**
 * The App context interface.
 */
export interface IAppContext {
    /**
     * The component to be rendered.
     */
    Component: () => JSX.Element;

    /**
     * Renderes the component.
     *
     * @param {Element | DocumentFragment | null} container The container. Optional parameter.
     */
    render: (container: Element | DocumentFragment | null) => void;

    /**
     * Gets the language.
     */
    getLanguage: () => string | undefined;

    /**
     * Sets the language.
     */
    setLanguage: (language?: string) => void;

    /**
     * Gets the theme.
     */
    getTheme: () => string | undefined;

    /**
     * Sets the theme.
     */
    setTheme: (theme?: string) => void;
}

interface IComponentProps {
    children: React.ReactNode;
    appState: IAppState;
    language?: string;
    languageSetEventHandler?: (language?: string) => void;
    languageUrlParam?: string;
    theme?: string;
    themeSetEventHandler?: (theme?: string) => void;
    themeUrlParam?: string;
}

/**
 * The App context builder.
 * Helps to build the App context and manage its state.
 */
export class AppContextBuilder {
    private props: IComponentProps = {
        children: undefined,
        appState: DefaultAppState,
        language: DefaultAppState.languageState,
        languageSetEventHandler: undefined,
        languageUrlParam: undefined,
        theme: DefaultAppState.themeState,
        themeSetEventHandler: undefined,
        themeUrlParam: undefined,
    };

    /**
     * Builds the App Context.
     *
     * @returns {IAppContext} The App Context Interface.
     */
    build() {
        const {
            language: initialLanguage,
            languageUrlParam,
            theme: initialTheme,
            themeUrlParam,
        } = this.props;

        const syncStateWithLocation = (appState: IAppState, location: Location) => {
            const {
                setLanguageState,
                setThemeState,
            } = appState;
            const pathname = deserializePathname(location.pathname);
            const language = languageUrlParam && pathname[languageUrlParam] && decodeURIComponent(pathname[languageUrlParam]);
            const theme = themeUrlParam && pathname[themeUrlParam] && decodeURIComponent(pathname[themeUrlParam]);
            language && setLanguageState && setLanguageState(language);
            theme && setThemeState && setThemeState(theme);
        };

        const syncLocationWithState = (appState: IAppState, history: History) => {
            const {
                languageState,
                themeState,
            } = appState;
            const pathname = deserializePathname(history.location.pathname);
            languageUrlParam && (pathname[languageUrlParam] = languageState && encodeURIComponent(languageState));
            themeUrlParam && (pathname[themeUrlParam] = themeState && encodeURIComponent(themeState));
            const serializedPathname = serializePathname(pathname);
            history.replace({ pathname: serializedPathname});
        };

        const Component = () => {
            const history = getHistory();
            const appState = AppState({
                language: initialLanguage,
                theme: initialTheme,
            });
            const {
                children,
                language,
                languageUrlParam,
                theme,
                themeUrlParam,
                ...rest
            } = this.props;
            React.useEffect(() => syncStateWithLocation(appState, history.location), []);
            React.useEffect(() => syncLocationWithState(appState, history), [appState, history]);
            this.props.appState = appState;
            return (
                <AppContextProvider {...rest} appState={appState}>
                    {children}
                </AppContextProvider>
            );
        };

        const render = (container: Element | DocumentFragment | null) =>
            ReactDOM.render(
                <React.StrictMode>
                    <Component />
                </React.StrictMode>,
                container || document.createElement('div')
            );

        const getLanguage = () => {
            const { languageState } = this.props.appState || {};
            return languageState;
        };

        const setLanguage = (language?: string) => {
            const { setLanguageState } = this.props.appState || {};
            setLanguageState && setLanguageState(language);
        };
        const getTheme = () => {
            const { themeState } = this.props.appState || {};
            return themeState;
        };

        const setTheme = (theme?: string) => {
            const { setThemeState } = this.props.appState || {};
            setThemeState && setThemeState(theme);
        };

        const context: IAppContext = {
            Component,
            render,
            getLanguage,
            setLanguage,
            getTheme,
            setTheme,
        };

        return context;
    }

    /**
     * Sets the children.
     * All the children within the context will have the same state.
     *
     * @param {(() => JSX.Element) | (Array<() => JSX.Element>)} children The children.
     */
    withChildren(children: (() => JSX.Element) | (Array<() => JSX.Element>)) {
        this.props.children = createChildren(children);
        return this;
    }

    /**
     * Sets the language. Default value: 'en'.
     *
     * @param {string} language The language.
     */
    withLanguage(language: string) {
        this.props.language = language;
        return this;
    }

    /**
     * Sets the language set event handler.
     *
     * @param {(language?: string) => void} languageSetEventHandler The language set event handler.
     */
    withLanguageSetEventHandler(languageSetEventHandler: (language?: string) => void) {
        this.props.languageSetEventHandler = languageSetEventHandler;
        return this;
    }

    /**
     * Sets the language url param to be synchronized with the language state.
     *
     * @param {string} languageUrlParam The language url param.
     */
    withLanguageUrlParam(languageUrlParam: string) {
        this.props.languageUrlParam = languageUrlParam;
        return this;
    }

    /**
     * Sets the theme. Default value: 'default'.
     *
     * @param {string} theme The theme.
     */
    withTheme(theme: string) {
        this.props.theme = theme;
        return this;
    }

    /**
     * Sets the theme set event handler.
     *
     * @param {(theme?: string) => void} themeSetEventHandler The theme set event handler.
     */
    withThemeSetEventHandler(themeSetEventHandler: (theme?: string) => void) {
        this.props.themeSetEventHandler = themeSetEventHandler;
        return this;
    }

    /**
     * Sets the theme url param to be synchronized with the theme state.
     *
     * @param {string} themeUrlParam The theme url param.
     */
    withThemeUrlParam(themeUrlParam: string) {
        this.props.themeUrlParam = themeUrlParam;
        return this;
    }
};

export default AppContextBuilder;
